### ISSUE TITLE
12 hour time showing incorrectly

### ISSUE THREAD

**Issue by NovaGL** [DBuit/sidebar-card#19]
I've enabled 12 hour time and it's showing AM instead of PM. The time is 13:40.

Is there a way I can fix it?

**Comment by ZacharyBallenger** [comment]
Having this same issue

**Comment by peteywhit** [comment]
Yep, I’m having the same problem. I see most others are using the 24 hour clock on the Home Assistant discussion.

I’ve tried making changes to the `sidebar-card.js` file, but it’s not reflecting the changes on my UI.

I can’t say definitively because I haven’t been able to get it to make any changes, but line 17421 defines variable `ampm` to pm if `hours >= 12`.

However `hours` is a constant defined below. This means the constant `hours` will always be less than 12. Which would lead to always being am.

```
const hours = ((date.getHours() + 11) % 12 + 1);
```

Here’s an example: It is currently 8:16pm CST.

```
date.getHours() = 20
20 + 11 = 31
31 mod 12 = 7
7 + 1 = 8
so...
8 < 12
```

It is the correct hour, but since `ampm` is pulling from this constant, then it is technically less than 12.

Hopefully, this is the problem, and @DBuit can verify.

Copied over from [](https://community.home-assistant.io/t/lovelace-custom-sidebar-card/174348/336)

**Comment by ThumpWump** [comment]
Having this same problem as well.... anybody have a solution yet?

**Comment by rogersmj** [comment]
@DBuit This is still a problem after 6+ months, would you mind please reviewing the PR?
