### ISSUE TITLE
Transparent background?

### ISSUE THREAD

**Issue by Salsalove** [DBuit/sidebar-card#52]
Which way to have a transparent background of the sidebar?

**Comment by GravityNL** [comment]
I'm trying to get it working to here.
i already tried hex codes and : rgba(255, 0, 0, 255); with no luck. NGL kinda a noob wen its comes to CSS

**Comment by crixle** [comment]
Not the creator, just providing some insight. The way the card works is by moving lovelace over to the side 20% (or whatever you set) and places the sidebar there. So it's two different elements, so when you set it to be transparent it doesn't have anything to reveal behind it.

**Comment by itsboo07** [comment]
> Not the creator, just providing some insight. The way the card works is by moving lovelace over to the side 20% (or whatever you set) and places the sidebar there. So it's two different elements, so when you set it to be transparent it doesn't have anything to reveal behind it.

is it possible to set a image as background of the sidebar?

**Comment by jwaz73** [comment]
In case you haven't found an answer to your question yet, yes.  I have done just that since the transparent sidebar was not an option.
![image](https://user-images.githubusercontent.com/35283565/204710113-b8c9bb4c-5e9f-4c52-a183-1f619e6fef8d.png)
(Sorry for the screenshot of the code.  Couldn't get the code formatting to work in GitHub tonight...)
![image](https://user-images.githubusercontent.com/35283565/204709619-54a482bd-1b13-48a9-b43b-915c4d97dad7.png)

**Comment by itsboo07** [comment]
@jwaz73 thanks....I too use the same way

**Comment by Ronny-1979** [comment]
Hello,
it is possible to make the background transparent. But only works with an animated background.


[https://github.com/dreimer1986/lovelace-animated-background](url)


https://github.com/DBuit/sidebar-card/assets/21090255/b11bca9c-c401-4356-b490-42f4dac55d19
