### ISSUE TITLE
Order position of options?

### ISSUE THREAD

**Issue by kzipp** [DBuit/sidebar-card#54]
Is there any way to change the position of the items (like get the clock on the bottom)? I should be able to do some with CSS but I was looking for a position or order placement option. Is something like that available or possible in the future?

**Comment by cismarine** [comment]
That would be nice.

**Comment by DBuit** [comment]
@CSchlipp dont know why it is closed but it can be done with CSS. with the `order` property.

Dont know how good your element inspect and css skills are but the sidebar contains a div with the class `sidebar-inner`.
Each element in this div are the base functions the sidebar has like the clock, menu, date, bottomCard etc.

To make it work you should add an order to each element otherwise it does not know where to put something so if you the css below you get the order as it is right now.

But change the order to -1 on one item and it will show first or just change it up.
1 thing the bottomCard got an extra `margin-top` property on it that makes sure it is on the bottom of the sidebar even when it got space above it, so if you change that one you should also add `margin-top: 0;` for the .bottom class.

Let me know if you get it working.

```
.digitalClock { order:1; }
.clock { order:2; }
.title { order:3; }
.date { order:4; }
.sidebarMenu { order:5; }
.template { order:6; }
.bottom { order:7; }
```
