### ISSUE TITLE
Can't cast to Google Hub using Google Cast

### ISSUE THREAD

**Issue by rdekoning11** [DBuit/sidebar-card#68]
When I attempt to cast a basic dashboard with the sidebar card, I get a big white space where the sidebar should be.

**Comment by cromelex** [comment]
I have the same issue, but rather than a white space the sidebard card doesn't seem to load and whater is on the rest of the dashboard will show, ie it seems like the page is being casted without the sidebar.

**Comment by DBuit** [comment]
The sidebar is outside the page view and so it is outside the view you are casting. It does at some css that is why you get the white. What i have is an view with an iframe card that loads my dashboard. I cast that view because it than also got my whole dashboard an can switch screen while casting.

I use this on a google hub so you can use the touch to switch view.

**Comment by cromelex** [comment]
> The sidebar is outside the page view and so it is outside the view you are casting. It does at some css that is why you get the white. What i have is an view with an iframe card that loads my dashboard. I cast that view because it than also got my whole dashboard an can switch screen while casting.
> 
> I use this on a google hub so you can use the touch to switch view.

would you be able to share some more details on how you are using that iframe card?
