### ISSUE TITLE
Style per template/<li> list item?

### ISSUE THREAD

**Issue by Newlance** [DBuit/sidebar-card#73]
I would like some of the list items to be bold.
I would LOVE to be able to insert a table as a list item.
It looks like the only HTML that works is that `<li> and </li> tag.`
I would even settle for being able to add a class or ID in that tag` (ie. <li class="bold">) `so that I could control the styles individually, but that too seems to break everything.  I'm not sure if this is a bug or a feature request, or I'm missing something obvious.

**Comment by daytonturner** [comment]
Similarly, I am trying to use the templating to display the currently playing song on one of my media players, including the album art thumbnail.  Originally I tried including an img tag but the  < > characters get urlencoded, therefore dont work.

Any idea on how to accomplish this, perhaps even with the class tag could help (since I will need to apply geometry parameters to the image as well)

**Comment by Scags104** [comment]
at the very least i would also love to see that empty tags allow a blank line. or <br> or something.  Currently using <li>.</li> in order to accomplish this and hate seeing the . between each template.
