### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by magtimmermans** [DBuit/sidebar-card#82]
Is this project dead? Please if so, let me know then I search for something else.

**Comment by Mr-HaleYa** [comment]
Pretty sure the creator uses it but is inactive so unless a bug comes up from a Home Assistant update that annoys them it's pretty dead... 2-year gap in updates then a couple in April due to 2023.4 bugs and another due to a 2023.5 bug

great project with great potential, sad to see development go stale.

**Comment by KentuckyMC** [comment]
Works fine for me, but indeed sad to see no further development in this. Also 9 pullrequests open. If you find something more active, please let us know :)
